### ISSUE TITLE
Provide downloadable executable for all three major platforms

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/yangster-electron#1]
Merged from https://github.com/theia-ide/yangster/issues/42:
 - [x] [When starting the application, it complains about the missing TS server](https://github.com/theia-ide/yangster/issues/42#issuecomment-342397219) (Fixed via e6a4dce81fd8fc9b8c2e5f0da6bbc9c70521398a)
 - [x] [I also got this when I have started the Yangster application and opened a `.yang.file`. Did not happen in the second start](https://github.com/theia-ide/yangster/issues/42#issuecomment-342397856) (See #3 )

**Comment by JanKoehnlein** [comment]
Shouldn't we just skip shipping the TS server? YANG user's are unlikely to need it.

**Comment by kittaakos** [comment]
I am fine with the solution too. I got the dependencies from [here](https://github.com/theia-ide/yangster/blob/master/yangster-app-electron/package.json), plus I have added Git.

**Comment by kittaakos** [comment]
The CI is handled in #7. The Windows bug is in #3. Closing this.
