### ISSUE TITLE
Build on all platforms

### ISSUE THREAD

**Issue by soerendomroes** [theia-ide/yangster-electron#26]
How are you able to build the different products for all os (I know, that I cannot build the dmg file for macOS on any other os)? Do you build them natively on each os?

**Comment by kittaakos** [comment]
Exactly. We use [AppVeyor](https://github.com/theia-ide/yangster-electron/blob/ea4c3d503bc016ed3f78352897771639ddf0989e/appveyor.yml#L28) for the Windows and [Travis-CI](https://github.com/theia-ide/yangster-electron/blob/ea4c3d503bc016ed3f78352897771639ddf0989e/.travis.yml#L34) for the Linux and OS X builds.
